### ISSUE TITLE
Consider automatic releases

### ISSUE THREAD

**Issue by bmish** [eslint-community/eslint-plugin-eslint-plugin#301]
_Originally posted by @MichaelDeBoey in https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/300#issuecomment-1243013325_

We currently use release-it to perform releases via a CLI command. I'm personally open to setting up the package to automatically release based on semantic commits. Any thoughts or recommendations on common/standard ways to do this?

**Comment by MichaelDeBoey** [comment]
In most of the projects I worked on, [`semantic-release`](https://github.com/semantic-release/semantic-release) was used to automatically create releases based on commits.

**Comment by aladdin-add** [comment]
release-it does support ci mode, sematic-release is more popular tho.
