### ISSUE TITLE
Delete the outdated `next` tag from NPM

### ISSUE THREAD

**Issue by bmish** [eslint-community/eslint-plugin-eslint-plugin#321]
The `next` tag for this package points to an old version. We can delete it as it's not in use now.

I believe this should do it for someone who has admin permissions.

```
npm dist-tag rm eslint-plugin-eslint-plugin next
```

https://www.npmjs.com/package/eslint-plugin-eslint-plugin

I can help with things like this and the publishing workflow if [I](https://www.npmjs.com/~bmishkin) receive NPM publishing privileges.

**Comment by MichaelDeBoey** [comment]
Removed it 👍
