### ISSUE TITLE
Date warning suggestion

### ISSUE THREAD

**Issue by arnotixe** [eslint-community/eslint-plugin-eslint-plugin#345]
This might be too narrow, to include in any standard distribution, but mentioning anyway.

I've made https://github.com/arnotixe/eslint-plugin-arnotixe/blob/master/README.md to warn on hyphens in javascript (frontend usage) Date() calls - Safari will crash on hyphens in Date() https://stackoverflow.com/questions/4310953/invalid-date-in-safari

(the app will crash, Safari will survive)

**Comment by bmish** [comment]
Thanks for the suggestion. eslint-plugin-eslint-plugin is only for lint rules related to writing ESLint plugins. It's sounds like your lint rule is targeted at any JavaScript code containing dates. You may want to search for an ESLint plugin related to dates or JavaScript language features instead.

**Comment by aladdin-add** [comment]
agreed with @bmish, it seems not a good fit for the plugin.
