### ISSUE TITLE
Error: Use `messageId` instead of `message` is incorrect for field `desc`

### ISSUE THREAD

**Issue by nopeless** [eslint-community/eslint-plugin-eslint-plugin#354]
This error will show if the suggestion has `desc` instead of `messageId`

The error message is misleading

I am willing to submit a PR

**Comment by bmish** [comment]
I assume you're talking about the `prefer-message-ids` rule. Yes, it would make sense to update the violation message to mention `desc` when reporting on a suggestion.

**Comment by nopeless** [comment]
so should I fix it

**Comment by bmish** [comment]
PR welcome!
