### ISSUE TITLE
Rule: Don't 'in' check AST nodes?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint-community/eslint-plugin-eslint-plugin#416]
From https://github.com/typescript-eslint/typescript-eslint/issues/8226:

> ### Suggestion
> Sometimes folks will use an `'in'` property check in a rule to narrow the type of a node:
> 
> ```ts
> declare const node: ts.BinaryExpression | ts.ConditionalExpression;
> 
> if ('condition' in node) {
>   node
>   // ^? const node: ts.ConditionalExpression
> }
> ```
> 
> I've been advising to prefer using less "dynamic" logical gates: existing type predicate functions, direct `.kind`/`.type` checks, and/or having different functions for different node selectors.
> 
> ```ts
> declare const node: ts.BinaryExpression | ts.ConditionalExpression;
> 
> // or:
> // if (node.kind === ts.SyntaxKind.ConditionalExpression) {
> if (ts.isConditionalExpression(condition)) {
>   node
>   // ^? const node: ts.ConditionalExpression
> }
> ```
> 
> My reasoning has been that "dynamic" logical gates, beyond being a potential deoptimization in JS perf, are susceptible to the types changing unexpectedly. E.g. a new version of TypeScript might add a new node type to a built-in union that adds a case previously meant to be caught by the rule.
> 
> My understanding of `in` checks is that they're generally reserved for cases where the more "static" ways of checking aren't available.
> 
> Shall we encode this as a lint rule?

Is this generally sound advice for lint rules altogether?

**Comment by aladdin-add** [comment]
I recognize its value, but it seems to be the type of information needed?

Otherwise there could be a lot of false positives (if obj is not an ast node):

```js
if( key in obj) {....}
```

**Comment by JoshuaKGoldberg** [comment]
Yeah, this would have to be a [typescript-eslint typed rule](https://typescript-eslint.io/linting/typed-linting) ([typescript-eslint > Custom Rules > Typed Rules](https://typescript-eslint.io/developers/custom-rules#typed-rules)).

**Comment by aladdin-add** [comment]
Currently no similar rules are included in this plugin, but I think it's possible, as long as it doesn't affect js users.
 / cc @bmish, would like to see your thoughts. 😄

**Comment by bmish** [comment]
It sounds useful to me.

Is this different from this one?

* https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/326

**Comment by JoshuaKGoldberg** [comment]
🤦 dear heavens. Sorry haha. I swear I did search for duplicates!
