### ISSUE TITLE
Update 'editor suggestions' link to point to user-facing guide

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint-community/eslint-plugin-eslint-plugin#422]
Right now, generated docs for rules with `meta.hasSuggestions` include:

> ```md
> 💡 This rule is manually fixable by [editor suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions).
> ```

That link is for developers working with rules. Most end-users don't want to go there.

As of https://github.com/eslint/eslint.org/issues/479 -> https://github.com/eslint/eslint/pull/17657, https://eslint.org/docs/latest/use/core-concepts#rule-suggestions is a new user-facing description of suggestions.

Would you accept a PR that updates the link?

**Comment by bmish** [comment]
I'm open to it. Should this be an issue in https://github.com/bmish/eslint-doc-generator?

**Comment by JoshuaKGoldberg** [comment]
D'oh, this is what happens when I file issues past midnight. Thanks. I'll send a PR there!
