### ISSUE TITLE
Provide suggestion or auto-fix for `require-meta-docs-recommended`

### ISSUE THREAD

**Issue by fisker** [eslint-community/eslint-plugin-eslint-plugin#478]
Make things easier if we provide suggestions or even auto-fix with `recommended: true`.

**Comment by aladdin-add** [comment]
I don't think it's reasonable to provide autofix - for many plugins it's a breaking change to change recommended config. 

Good to provide two suggestions: `recommended: true` and `recommended: false`. Are you willing to submit a PR? :)

**Comment by fisker** [comment]
> Are you willing to submit a PR? 

Not really, the only plugin I maintain is already fixed 😄 https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2336/files
